allow_run_while_formatting = false
edition = "2024"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
condense_wildcard_suffixes = true
newline_style = "Unix"
